### ISSUE TITLE
Use six for python 2/3 compatibility

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#22]
There's a few try/catch blocks around boatd for compatibility with python 2 and 3. We should instead use [six](https://pythonhosted.org/six/), since it's a well maintained module to avoid this boilerplate.

**Comment by Danyc0** [comment]
So setup.py seemingly uses setuptools for python 3, and distutils.core for python 2, but setuptools seems like it's supported by both python 2 and 3, so why use distutils.core at all?

**Comment by kragniz** [comment]
Implemented in 39e444a2bb173de0d8c2f9e2931e23d804f9b8db by @Danyc0
