### ISSUE TITLE
Perform filtering of wind angle

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#41]
Average the absolute wind direction over time. Make the API return the averaged value.

**Comment by SamStudio8** [comment]
SOUNDS LIKE SOMEONE NEEDS A KALMAN FILTER

**Comment by kragniz** [comment]
Nah, just an average over time will be good enough. Something very similar to: https://github.com/abersailbot-archive/sailbot2013/blob/master/sailbot/boat.py#L93-L100

**Comment by kragniz** [comment]
Added in 2178468b929efdc967867510571a035f13288a3c
