### ISSUE TITLE
Consider renaming "current" to "active" or "running"

### ISSUE THREAD

**Issue by zuzak** [boatd/boatd#55]
According to the documentation, POSTing to `/behaviours` gives you some JSON showing the currently running behaviour. This is listed as `"current"`, which is a rather [overloaded term](https://en.wikipedia.org/wiki/Ocean_current). Maybe one should rename this to `"active"`, or bring it in line with the equivalent GET request by naming it `"running"` ([although this is also means a thing](https://en.wikipedia.org/wiki/Point_of_sail#Running_downwind)).

**Comment by kragniz** [comment]
Good idea.
