### ISSUE TITLE
Remove ambiguity in which coordinate system wind direction is in

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#58]
There were a few problems where it was not clear whether the returned wind direction was in global coordinates or relative to the boat's current heading. Perhaps the API should return `relative_direction` and `global_direction`, or two other terms to disambiguate.

This will also require a change to python-boatdclient.

**Comment by thip** [comment]
mine

**Comment by Danyc0** [comment]
Should be 'apparent wind' not 'relative wind' to remove ambiguity
