### ISSUE TITLE
Inadequate documentation

### ISSUE THREAD

**Issue by colinsauze** [boatd/boatd#7]
The documentation does not explain the following:

* How to start boatd 
* How to configure boatd and configure it to run a behaviour/driver.
* How the directory structure of boatd and its behaviours/drivers should be laid out. Especially when boatd has been installed via pip, should the drivers and behaviours be in system directories, this is not made clear.

**Comment by kragniz** [comment]
I'm going to say this is mostly there. There's a fair amount of documentation now at http://boatd.readthedocs.io/

Further problems with the documentation should have new issues created for them.
